language: node_js
node_js:
 - 10.17.0
branches:
  only:
  - development
before_deploy:
  - npm run build
deploy:
  provider: s3
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  bucket: voicesofthepandemic.dbknews.com
  acl: public_read
  local_dir: build
  skip_cleanup: true
  on:
    branch: development
after_deploy:
  - echo "Static site deployed"
